INSERT INTO items (name, description, "imgUrl", "createdAt", "updatedAt")
VALUES 
('baby care', 'DESCRIPTION', now(), now()), 
('bread bakery', 'DESCRIPTION', now(), now()), 
('canned jarred goods', 'DESCRIPTION', now(), now()), 
('condiments sauces', 'DESCRIPTION', now(), now()), 
('deli', 'DESCRIPTION', now(), now()), 
('diary', 'DESCRIPTION', now(), now()), 
('drinks beverages', 'DESCRIPTION', now(), now()), 
('fish seafoods', 'DESCRIPTION', now(), now()), 
('frozen foods', 'DESCRIPTION', now(), now()), 
('fruits', 'DESCRIPTION', now(), now()), 
('health care', 'DESCRIPTION', now(), now()), 
('household supplies', 'DESCRIPTION', now(), now()), 
('kitchen supplies', 'DESCRIPTION', now(), now()), 
('meat', 'DESCRIPTION', now(), now()), 
('nuts seeds', 'DESCRIPTION', now(), now()), 
('paper wrap', 'DESCRIPTION', now(), now()), 
('pasta rice cereals', 'DESCRIPTION', now(), now()), 
('personal care', 'DESCRIPTION', now(), now()), 
('pet care', 'DESCRIPTION', now(), now()), 
('snacks', 'DESCRIPTION', now(), now()), 
('spices herbs', 'DESCRIPTION', now(), now()), 
('vegetables', 'DESCRIPTION', now(), now()), 